# See user_config.inc for build customization
-include user_config.inc
include default_config.inc


.PHONY: all clean

all: svm40_example_usage

svm40_example_usage: clean

clean:
	$(RM) svm40_example_usage
